apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
  labels:
    app: java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java
  template:
    metadata:
      labels:
        app: java
    spec:
      imagePullSecrets:
        - name: ecr-creds
      containers:
        - name: java
<<<<<<< HEAD
          image: 485492729952.dkr.ecr.us-east-1.amazonaws.com/iti:v29
=======
          image: 485492729952.dkr.ecr.us-east-1.amazonaws.com/iti:v30
>>>>>>> fb05120ae99151049c718f0a427f1cf616b1bfd4
          ports:
            - containerPort: 8090
